import Head from "next/head"
import axios from "axios"
import markdownToHtml from "../utils/MarkdownToHTML";


export async function getStaticProps() {
  const res = await axios.get("http://localhost:1337/api/book-reviews/");
  const posts = res.data;
  const content = await markdownToHtml(posts.data[0].attributes.content);
  return {
    props: {
      posts,
      content
    }
  }
}

export default function Home({ posts, content }) {
  console.log(posts);
  return (
		<div className="container">
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className="main">
				<h1> Hi! Welcome to my blog</h1>

				<div>
          {posts.data.map((post) => {
            return (
              <div key={post.id}>
                <h2>{post.attributes.Title}</h2>
                <div dangerouslySetInnerHTML={{__html: content}}></div>
              </div>
            )
          })}
        </div>
			</main>

			<footer className="footer"></footer>
		</div>
	);
}
